select
   PACFIN_SPECIES_CODE spid,
   sample_year,
   sample_month,
   sample_day,
   sample_agency,
   SAMPLE_METHOD_CODE sample_method,
   sample_type,
   agency_code source_agid,
   SAMPLE_NUMBER sample_no,
   CLUSTER_SEQUENCE_NUMBER cluster_no,
   FRAME_CLUSTER_WEIGHT_LBS frame_clwt,
   CLUSTER_WEIGHT_LBS cluster_wgt,
   ADJUSTED_CLUSTER_WEIGHT_LBS adj_clwt,
   SPECIES_WEIGHT_LBS species_wgt,
   PACFIN_PORT_CODE pcid,
   AGENCY_PORT_CODE port,
   AGENCY_GEAR_CODE gear,
   PACFIN_GEAR_CODE grid,
   data_type,
   PSMFC_CATCH_AREA_CODE PSMFC_ARID,
   ftid,
   DEPTH_AVERAGE_FATHOMS depth_avg,
   DEPTH_MINIMUM_FATHOMS depth_min,
   DEPTH_MAXIMUM_FATHOMS depth_max,
   PACFIN_CONDITION_CODE cond,
   AGENCY_CONDITION_CODE cond_agcode,
   FISH_LENGTH_TYPE_CODE fish_length_type,
   FISH_LENGTH,
   FORK_LENGTH,
   FORK_LENGTH_IS_ESTIMATED fork_length_estimated,
   FISH_MATURITY_CODE maturity,
   AGENCY_FISH_MATURITY_CODE maturity_agcode,
   FISH_WEIGHT,
   SEX_CODE sex,
   WEIGHT_OF_MALES_LBS males_wgt,
   NUMBER_OF_MALES males_num,
   WEIGHT_OF_FEMALES_LBS females_wgt,
   NUMBER_OF_FEMALES females_num,
   WEIGHT_OF_LANDING_LBS total_wgt,
   EXPANDED_SAMPLE_WEIGHT exp_wt,
   AGE_METHOD_CODE age_method,
   AGE_READABILITY age_readability,
   FINAL_FISH_AGE_IN_YEARS age_years,
   FINAL_FISH_AGE_IN_YEARS fish_age_years_final,
   FINAL_FISH_AGE_CODE fish_age_code_final,
   AGE_SEQUENCE_NUMBER agenum,
   PERSON_WHO_AGED aged_by,
   DATE_AGE_RECORDED date_aged,
   AGE_STRUCTURE_CODE age_struct_agcode,
   OBSERVED_FREQUENCY freq
FROM pacfin_marts.COMPREHENSIVE_BDS_COMM
WHERE
   PACFIN_SPECIES_CODE LIKE upper(&sp) AND
   sample_year between &beginyr and &endyr
ORDER BY
   sample_year,
   sample_agency;
